### ISSUE TITLE
Change yaxis on the spectrogram

### ISSUE THREAD

**Issue by matiasandina** [zekebarger/AccuSleep#5]
It would be awesome to have the `ylim` of the spectrogram go in breaks of 5 instead of breaks of 10.
I managed to hack it by adding the code below after line 255 on `AccuSleep_viewer.m`, but probably this is an easy fix for you.

```
yticklabels = 0:5:30;
set(G.A3, 'Ytick', yticklabels(:), 'YTickLabel', yticklabels(:)); 
```
This helps to see if we are below 5 Hz and whether we are on the delta or theta range

**Comment by zekebarger** [comment]
Just pushed this change, thanks for the feedback!
