### ISSUE TITLE
Data length problems in OSF datasets

### ISSUE THREAD

**Issue by matiasandina** [zekebarger/AccuSleep#8]
Hello,
I am trying to use the sample data to train but I am facing some off-by one errors.
Most of the files have labels of length 17279, while the EEG epochs should be 17280, given sampling rate is 512 and epoch length is 2.5 seconds.

I compiled a table with the files that have issues. It looks as if the raw data is correct, but the labels are missing one. I tried to load this data into `AccuSleep` but got the error regarding file lengths.

[file_lengths.csv](https://github.com/zekebarger/AccuSleep/files/8548114/file_lengths.csv)

By the way, this is not an issue with the 4hr recordings, the lengths match for those :). Any inputs appreciated!

**Comment by zekebarger** [comment]
Thanks for catching that! I just fixed the label files on OSF.
